"""add assignment_id to notifications

Revision ID: fda92559ede5
Revises: d31532b87160
Create Date: 2026-07-10 14:25:21.399630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fda92559ede5'
down_revision: Union[str, Sequence[str], None] = 'd31532b87160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('assignment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'assignments', ['assignment_id'], ['assignment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'assignment_id')
    # ### end Alembic commands ###
